---
title: 오류 전달 방법
author: bayernmuller
---

* 오류가 발생하면 일반적으로 더 높은 계층으로 오류를 알려야한다.
* 오류를 알리는 방법은 크게 두가지로 나뉜다.
    * **명시적 방법**: 코드를 호출한 쪽에서 오류가 발생할 수 있음을 인지할 수밖에 없도록 한다.
        * 어떻게 처리할지는 호출하는 쪽에서 결정한다.
    * **암시적 방법**: 코드를 호출하는 쪽에 오류를 알리지만 호출하는 쪽에서 신경쓰지 않아도 되도록 한다.

| | 명시적 방법 | 암시적 방법 |
| --- | --- | --- |
| **코드 계약에서의 위치** | 명확한 부분 | 세부조항 혹은 아예 없음 |
| **호출하는 쪽에서 오류 발생 가능성을 아는가?** | 네 | 알 수도 있고 모를 수도 있음 |
| **예시** | 검사 예외, 널 반환 유형, 옵셔널 반환 유형, 아웃컴 반환 유형, 스위프트 오류 | 비검사 예외, 매직값 반환, 프로미스 또는 퓨쳐, 어서션, 체크, 패닉 |

### 4.3.1 요약: 예외

* 예외는 발생하면 콜 스택을 거슬로 올라가 예외를 처리하는 코드 (catch, except..)를 만나거나 더이상의 콜 스택이 없을 떄까지 그렇게 한다.
* 예외는 일반적으로 클래스로 구현되며 개발자는 오류에 대한 정보를 자유롭게 정의하고 캡슐화 할 수 있다.

```python
class MyException(Exception):
    pass
```

```c++
class MyException : public std::exception {
    public:
        const char* what() const noexcept override {
            return "MyException";
        }
};
```

### 4.3.2 명시적 방법: 검사 예외
> checked exception

#### 검사 예외를 사용한 오류 전달
```java
class NegativeNumberException extends Exception {
    private final Double erroneousNumber;

    NegativeNumberException(Double erroneousNumber) {
        this.erroneousNumber = erroneousNumber;
    }

    Double getErroneousNumber() {
        return erroneousNumber;
    }
}

Double getSquareRoot(Double number) throws NegativeNumberException {
    if (number < 0.0) {
        throw new NegativeNumberException(number);
    }
    return Math.sqrt(number);
}
```

* 위 코드에서 `getSquareRoot` 함수는 인자로 받은 숫자가 음수인 경우 `NegativeNumberException` 예외를 던진다.
* `getSquareRoot` 함수 시그니처에는 이 함수가 어떤 예외를 던질 수 있는지 명시되어 있고 함수에서 해당 예외를 던지지 않으면 컴파일 오류가 발생한다.

#### 검사 예외 처리

```java
void displaySquareRoot(Double number) {
    try {
        Double result = getSquareRoot(number);
        System.out.println(result);
    } catch (NegativeNumberException e) {
        System.out.println("Cannot compute square root of negative number: " + e.getErroneousNumber());
    }
}
```
* 이처럼 재정의 한 `NegativeNumberException` 클래스의 인스턴스는 예외의 원인이 된 숫자를 담고 있고 이를 통해 예외의 원인을 파악할 수 있다.
* 여기서 만약 `displaySquareRoot` 함수가 예외를 처리하지 않으면 이 함수 자체도 예외를 던질 수 있는 함수가 되므로 `throws NegativeNumberException` 을 명시해야 한다.

```java
void displaySquareRoot(Double number) throws NegativeNumberException {
    Double result = getSquareRoot(number);
    System.out.println(result);
}
```

* 예외를 무시하고 코드를 작성하면 결국에 컴파일이 되지 않기 때문에 명시적 방법으로 오류를 전달하고 있다고 할 수 있다.

### 4.3.3 암시적 방법: 비검사 예외
> unchecked exception

* 비검사 예외를 사용하면 코드가 이 예외를 발생시킬 수 있다는 사실을 모를 수 있다. -> 암시적 방법

#### 비검사 예외를 사용한 오류 전달

```java
class NegativeNumberException extends RuntimeException {
    private final Double erroneousNumber;

    NegativeNumberException(Double erroneousNumber) {
        this.erroneousNumber = erroneousNumber;
    }

    Double getErroneousNumber() {
        return erroneousNumber;
    }
}

Double getSquareRoot(Double number) { // 함수 시그니처에 예외 명시 안함
    if (number < 0.0) {
        throw new NegativeNumberException(number);
    }
    return Math.sqrt(number);
}
```

* 위 코드에서 `getSquareRoot` 함수는 인자로 받은 숫자가 음수인 경우 `NegativeNumberException` 예외를 던지지만 함수를 호출하는 쪽에서 예외를 처리하지 않아도 컴파일 오류가 발생하지 않는다.

#### 비검사 예외 처리

* 비검사 예외를 던졌을 때 예외는 콜스택을 거슬러 올라가 결국 예외 처리 코드를 만나지 못하면 프로그램이 종료된다.

### 4.3.4 명시적 방법: 널값이 가능한 반환 유형

* NULL 을 반환하는 것은 특정 값을 계산하거나 얻는 것이 불가능함을 나타내기 위한 방법 중 하나이다.
* 사용중인 언어가 null-safety 를 지원한다면 호출하는 쪽에서 리턴값이 NULL 이 될 수 있음을 강제로 인식하고 처리해야한다.

#### NULL 값을 이용한 오류 전달

```python
# if user_id is not found, return None
def get_user_by_id(user_id: int) -> User | None:
    result = db.get_user_by_id(user_id)
    if not result:
        return None
    return result
```
* NULL 오류 전달은 오류가 발생한 이유에 대한 정보를 전달하지 않기 때문에 NULL 이 의미하는 바를 명시해야한다. (여기서는 주석)


#### 널값 처리
```python
def display_user(user_id: int):
    user = get_user_by_id(user_id)
    if user is None:
        print("User not found")
        return
    print("User found: " + user.name)
```
* 호출하는 쪽에서 리턴 값을 확인하고 분기하여 처리한다.

### 4.3.5 명시적 방법: 리절트 반환 유형

* Swift 나 Rust 같은 언어는 Result 라는 타입을 제공한다.
* 쉽게 말해 리턴 값은 오류가 될 수도, 정상 값이 될 수도 있는 방법이다.


#### 리절트 유형을 이용한 전달
```rust
fn get_user_name_by_id(user_id: u32) -> Result<String, Error> {
    match db.get_user_by_id(user_id) {
        Some(user) => Ok(user.name),
        None => Err(Error::UserNotFound),
    }
}
```

#### 리절트 처리
```rust
fn display_user(user_id: u32) {
    match get_user_name_by_id(user_id) {
        Ok(user) => println!("User found: {}", user),
        Err(e) => println!("Error: {}", e),
    }
}
```

#### 4.3.6 명시적 방법: 아웃컴 반환 유형

* 어떤 함수들은 값을 반환하지 않고 무언가 수행하지만 한다.
* 이런 함수들은 동작의 성공 여부를 반환 값으로 알려주도록 바꿀 수 있다.

#### 아웃컴을 이용한 오류 전달

```python
def send_message(channel: Channel, message: str) -> bool:
    if channel.is_available():
        channel.send(message)
        return True
    return False
```
* 참/거짓 만으로 성공 여부를 알려주기 힘든 경우에 Enum 타입을 사용할 수도 있고, 리턴 타입을 클래스로 정의하는 것도 방법이다.

#### 아웃컴 처리

```python
def say_hello(channel: Channel):
    if (send_message(channel, "Hello")):
        print("Message sent")
    else:
        print("Message failed to send")
```

#### 아웃컴이 무시되지 않도록 보장

* 아웃컴 반환 방식의 문제는 호출하는 쪽에서 아웃컴을 무시할 수 있다는 점이다.

```python
def say_hello(channel: Channel):
    send_message(channel, "Hello") # return 값이 무시됨
    print("Message sent")
```

* 일부 언어에서는 리턴 값이 무시되지 않도록 경고를 발생시킬 수 있다.

#### 4.3.7 암시적 방법: 프로미스 또는 퓨처

#### 프로미스를 이용한 오류 전달

```java
class NegativeNumberException extends Error {
    ...
}

Promise<Double> getSquareRoot(Double number) async {
    await Timer.wait(Duration.ofSeconds(1));
    if (number < 0.0) {
        throw new NegativeNumberException(number);
    }
    return Math.sqrt(number);
}
```

* `getSquareRoot` 는 호출되었을 때 1초를 쉬고 값을 판단한 뒤 정상적인 값을 반환하거나 예외를 던진다.
* 예외를 발생 시키면 Promise 는 거부되고, 값을 반환하면 이행된다.

#### 프로미스 처리

```java
void displaySquareRoot(Double number) {
    getSquareRoot(number)
        .then(squareRoot ->
            System.out.println(squareRoot))
        .catch(e ->
            System.out.println("Error: " + e));
}
```

#### 왜 프로미스는 암묵적인 오류 전달 기법인가

* 호출하는 쪽에서 잠재적인 오류 시나리오를 완전히 알지 못하기 때문이다.

#### 프로미스를 명시적으로 만들기

```java
Promise<Result<Double, NegativeNumberException>> getSquareRoot(Double number) async {
    ...
}
```
* 프로미스와 리절트를 함께 사용하여 오류를 명시적으로 전달할 수 있다.

### 4.3.8 암시적 방법: 매직값 반환

* 어떤 값에 특별한 의미를 부여하여 오류로 간주하게 하는 방법이다.

```c
#include <unistd.h>

int main() {
    int fd = open("bayernmuller.txt", O_RDONLY);
    if (fd == -1) {
        return 1;
    }
    close(fd);
    return 0;
}
```

* 여기서 `-1` 은 파일을 열 수 없음을 나타내는 매직값이다.
* 매직 값은 호출하는 쪽에 오류의 이유를 알릴 수도 없고, 버그로 이어질 수 있어 좋은 방법은 아니다.